import Head from 'next/head'
import Image from 'next/image'
import react,{useState, useEffect} from 'react'
import { useRouter } from 'next/router'
import axios from 'axios'

export default function Home() {
  const router = useRouter()
  const [account,setAccount] = useState('')
  const [password,setPassword] = useState('')
  const [btncolor,setBtncolor] = useState('bg-neutral-200')
  const [inputsuccess,setInputsuccess] = useState(false)

  function sendAccount(e) {
    e.preventDefault()
    if(!inputsuccess)  return  
    checkAuth()
  }

  async function checkAuth(){
    try{
      const user = await axios.post(`http://18.181.110.2:7000/api/auth/login`,{
        account,
        password
      })
      if(user.status === 200){
        router.push('/dashboard/user')
      }
    }catch(err){
      alert('帳密錯誤')
      setAccount('')
      setPassword('')
    }  
   
  }

  useEffect(() => {
      if(account !== '' && password !== ''){
        setBtncolor('bg-neutral-600')
        setInputsuccess(true)
      }else{
        setBtncolor('bg-neutral-200')
        setInputsuccess(false)
      }
  },[account,password])

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full h-screen'>
        <div className='w-full h-[10%] bg-neutral-100 flex items-center'>
            <a href="http://localhost:3000/" >
                <img src="/images/phalanity.gif" alt="" className='w-[15%] object-contain'/>
            </a>
        </div>

        <section className='w-full h-3/5 flex justify-center items-center'>
            <div className='w-1/5 h-3/5 xl:w-2/5 sm:w-3/5'>
                <h1 className='text-center font-bold h-2/5 text-3xl text-zinc-600'>登入</h1>
                <form className='flex flex-col h-3/5 justify-around' onSubmit={e => sendAccount(e)}>
                    <input type="text" placeholder='帳號' className='border-b h-12 outline-0 focus:border-zinc-600 placeholder:text-zinc-600'
                        onChange={e => setAccount(e.target.value)}
                        value={account}
                    />
                    <input type="password" placeholder='密碼' className='border-b h-12 outline-0 focus:border-zinc-600 placeholder:text-zinc-600'
                        onChange={e => setPassword(e.target.value)}
                        value={password}
                    />
                    <button className={`h-12 w-full font-bold ${btncolor} text-white ${(btncolor === 'bg-neutral-600') && 'hover:bg-yellow-300'}`}>SIGN IN</button>
                </form>
            </div>
        </section>
      </main>

    </div>
  )
}
